name: Deploy website

on:
    push: 
        branches: [main]

permissions: 
    contents: write # for gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.4.0
      - uses: extractions/setup-just@v2
      - run: just web
      - uses: actions/setup-node@v4.2.0
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          touch package.json
          npx gh-pages -d web -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
